export const messageApi = {
  // common
  SUCCESS: 'REQUEST SUCCESSFULLY',
  FAIL: 'REQUEST FAILURE',

  // user
  CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',

  // Fail 
  CREATE_PRODUCT_FAIL_FIELD: 'CREATE PRODUCT FAILURE. PLEASE ENOUND INFORMATION',
};
